### ISSUE TITLE
Modbus stops working to HA when battery turned on.

### ISSUE THREAD

**Issue by MatcherMike** [alienatedsec/solis-ha-modbus-cloud#13]
Hi,

Firstly, many thanks gor helping with my ha integration on the other thread. I'm happy I get figures except the ct pv generation value.

I have replicated your setup. Thanks for the great detail. I get values into HA, except, when I turn the power switch on my battery on! I then get no new values. For example, Meter active power stays old and the minutes since update count up. There is little to no flashing of the activity blue led.

Turn off the battery and within 30seconds the values update. 

Ip comms work ok to the modbus adapters throughout

Any ideas please?

Inverter is solis ac.

Thanks
Mike

**Comment by alienatedsec** [comment]
@MatcherMike 
I am not sure which option you activate and which is not working - please can you paste any screenshots? Also, I would need more about your setup i.e. Inverter model and which integration is used.

**Comment by MatcherMike** [comment]
Hi, sorry for the delay in replying. I still don't have this working and have been running with the datalogger direct into the inverter. I have today conducted some further testing.

Inverter: SN 060262225140105
Type: rai-3k-48es-5g
Operation: Grid connected AC battery only mode (Not Hybrid)
Battery: Seplos BMS with 16x Cells
Datalogger:  S3-WIFI-ST
HA Version: 2023.5.4, Supervisor 2023.04.1, Operating System 10.2
HA Integration: https://github.com/wills106/homeassistant-solax-modbus, Using Solis inverter type - Version 2023.05.2

If i have my battery system (seplos BMS) turned off, then i get soliscloud stats ok. I also have stats into HA using the above integrations:

![SolisModbus Working](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/b1eddd4f-b51f-40bc-b5f0-f0e6a4d84894)
![SolisModbus Integration](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/af1f2084-0c51-4832-b36e-7f7224498fad)
![Screenshot_20230531_122607_SolisCloud](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/04b66889-d85c-4ed2-b016-96d10000b652)

If i turn my battery system on, it all stops working:
![SolisModbus Unavailable](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/f6a20b0b-47b5-4c82-94e8-1a00b98c1cc9)
![SolisModbus Unavailable 2](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/29bad0b5-e4cc-4e30-8642-d186344b5924)

Stats in solis cloud remain static, until they eventually disappear.

Here is the connectivity of my system:

![20230531_122341](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/22170496-87aa-4c63-92dd-677c9555955d)
![20230531_122721](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/cab965c7-7167-41e3-a3b7-844869f1e702)
![20230531_122824](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/25ad9dda-9ca8-4179-909f-6d636eca8d0d)
![modbus adapter 1](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/ebdfa36d-70a6-439b-a1e8-b682adfc2230)
![modbus adapter 2](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/121827283/b485e7cb-0921-48e1-9493-2a571d891ae8)

I have no idea why turning the battery on, would stop it all working!
My solis modbus integration does still complain about the serial number of the inverter, but it pulls stats into HA ok.

Happy to take more screenshots, and to try anything. Really appreciate your help with this.
Mike

**Comment by alienatedsec** [comment]
@MatcherMike is the BMS IP connected? If so, it may have the same IP as your TCP Server and conflict when turned on at the same time.

**Comment by MatcherMike** [comment]
> @MatcherMike is the BMS IP connected? If so, it may have the same IP as your TCP Server and conflict when turned on at the same time.

Good question. No it has no IP connectivity. Just the RS485 CAN connection to the Inverter. I currently manage it via BT.

I have previously connected to it via RS485 adapter for adjusting some settings.

**Comment by alienatedsec** [comment]
What settings? Are those configurable on both, the inverter and the BMS?

**Comment by MatcherMike** [comment]
I had to set the communications type on the BMS and the inverter to get the CAN working. These are the only changes

Seplos documentation is here: https://drive.google.com/drive/folders/10pxgNLHovcDZRVGrCZsSkfecBrRw-AdW

**Comment by MatcherMike** [comment]
I think i may have resolved this now - I removed my earth grounding for the two waveshare units, and i now have stats through HA modbus and solis cloud. Not sure why this would cause an issue.

Will test further through tomorrow,
Thanks

**Comment by alienatedsec** [comment]
> earth grounding

Which one? Earth and ground has different connections and technically both are slightly different. 

https://byjus.com/physics/difference-between-earthing-and-grounding/

Where did you connect your earth (green) cables?

**Comment by MatcherMike** [comment]
Pgnd, the leftmost connector on the top of the waveshare. I had this connected to an electrical earth point. Same earth point as my inverter and battery system.  Confused as it worked normally, but not with battery on.

Where did you connect yours?

Thanks

**Comment by alienatedsec** [comment]
> Where did you connect yours?

There is an earth rod behind my garage. The same connected to my inverter's radiator. I connected it directly there.

**Comment by MatcherMike** [comment]
That's effectively what i had her. No worries, seems like it isn't necessary and hopefully continues to work.

Many thanks for responding, and many thanks for putting together this great guide.
