### ISSUE TITLE
Din rail screws

### ISSUE THREAD

**Issue by wawyed** [alienatedsec/solis-ha-modbus-cloud#33]
Hi, I was wondering if you had some more info on which din rai l/ screws to get for the Sourcingmap 240mm x 160mm x 90mm Plastic Dustproof IP65 DIY Junction Box Power Protection

**Comment by alienatedsec** [comment]
Hi @wawyed 

This part is `hit and miss`, so I would suggest picking a box that has a DIN rail built-in.

For Example
https://www.amazon.co.uk/gp/aw/d/B09ZYD6DYM/

![image](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/73167064/7a899ea2-dd7d-4c23-bd86-f677b65ceecb)

**Comment by wawyed** [comment]
Thank you

**Comment by solarjones** [comment]
I bought this small length of rail https://www.ebay.co.uk/itm/174372581661 and used araldite to glue it in place.
