### ISSUE TITLE
Modbus RS485 to wifi instead of 2 waveshare units

### ISSUE THREAD

**Issue by stewwy** [alienatedsec/solis-ha-modbus-cloud#36]
Would this be possible? Replace the 2 waveshare units with this?

https://thepihut.com/products/rs485-to-wifi-ethernet-module-modbus-mqtt-gateway

As they should appear as 2 different things with the same information on the wifi network

**Comment by alienatedsec** [comment]
@stewwy in short, this unit will not work properly https://homeassistant-solax-modbus.readthedocs.io/en/latest/compatible-adaptors/#non-working-troublesome-rs485-adaptors
